### ISSUE TITLE
targetingInfo

### ISSUE THREAD

**Issue by Motero69** [googlecodelabs/admob-ads-in-flutter#1]
Just to Know,  in the example Adding AdMob ads to a Flutter app, never talk or put the "targetingInfo"   
like say in the package information.

Its ok with out that information?

**Comment by kunny** [comment]
If you use `firebase_admob` `0.9.3+3` or higher, you can remove `targetingInfo` section from the code.

(That line exists to avoid the bug(FirebaseExtended/flutterfire/issues/44), which was fixed in 0.9.3+3)
