### ISSUE TITLE
Typo for label when is iOS adUnit.

### ISSUE THREAD

**Issue by Lokocr** [googlecodelabs/admob-ads-in-flutter#13]
Hi guys.

I was implementing the ads for my app in flutter following the codelab and found this Issue.

![image](https://user-images.githubusercontent.com/1214120/121985808-b1447c80-cd52-11eb-8073-583d6eb139fa.png)

I mark the mistake but to explain.

When is implementing the iOS adUnit, the placeholder for it say: _YOUR_ANDROID_INTERSTITIAL_AD_UNIT_ID_ but has to say: _YOUR_IOS_INTERSTITIAL_AD_UNIT_ID_ instead.

Since when we create the adUnit is true you can use the same, but for tutorials intend I think is better to be more clear. 

Thanks for your hard work.

**Comment by kunny** [comment]
Thanks for filing the issue! I'll fix the content, and will let you know once it's complete.

**Comment by kunny** [comment]
Just rolled out the change:) https://codelabs.developers.google.com/codelabs/admob-ads-in-flutter#4
