### ISSUE TITLE
Deprecated

### ISSUE THREAD

**Issue by Sebastien-Remy** [googlecodelabs/admob-ads-in-flutter#15]
The plugin used is deprecated

**Comment by tempral** [comment]
Note: F:\apps\flutter\.pub-cache\hosted\pub.dartlang.org\google_mobile_ads-0.13.0\android\src\main\java\io\flutter\plugins\googlemobileads\FlutterAdSize.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.jetbrains.kotlin.com.intellij.util.ReflectionUtil (file:/C:/Users/carmi/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-compiler-embeddable/1.4.32/b4fc9be460ca88eecea2303e142ce2920bd14775/kotlin-compiler-embeddable-1.4.32.jar) to method java.util.ResourceBundle.setParent(java.util.ResourceBundle)
WARNING: Please consider reporting this to the maintainers of org.jetbrains.kotlin.com.intellij.util.ReflectionUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by kunny** [comment]
@Sebastien-Remy: I recently updated the English version, but it's not translated into other languages yet. Could you check English version for the time being?

@tempral: It's an issue should be handled by the `google_mobile_ads` plugin. Please use https://github.com/googleads/googleads-mobile-flutter/issues instead. Thanks!
