### ISSUE TITLE
can't see any ads on a release build

### ISSUE THREAD

**Issue by tempral** [googlecodelabs/admob-ads-in-flutter#16]
the quiz work propely, but no ads are shown

**Comment by lecongphu** [comment]
Why?

**Comment by kunny** [comment]
You may want to check why ad failed to load by setting `onAdFailedToLoad` callback. (e.g., https://github.com/googleads/googleads-mobile-flutter#banner-ad-events)

Please refer to `LoadAdError.message` for details.
