### ISSUE TITLE
Error Loading Test Ads

### ISSUE THREAD

**Issue by UsamaEjaz0** [googlecodelabs/admob-ads-in-flutter#17]
I get the following error and my test ads don't load due to it.

W/chromium( 8405): [WARNING:cookie_manager.cc(392)] Strict Secure Cookie policy does not allow setting a secure cookie for http://googleads.g.doubleclick.net/

**Comment by kunny** [comment]
I believe it's a warning message generated from the SDK side, not relate to ad serving itself. I've seen apps showing ads while the above error message is being logged.

I would encourage you to check the error code to check the details (via `onAdFailedToLoad` callback) to see what's blocking the ad from being served. :)
