### ISSUE TITLE
RewardedAd missing steps

### ISSUE THREAD

**Issue by beersheba** [googlecodelabs/admob-ads-in-flutter#18]
There are missing steps in [Section 9 (Add a rewarded ad)](https://codelabs.developers.google.com/codelabs/admob-ads-in-flutter?hl=en&continue=https%3A%2F%2Fcodelabs.developers.google.com%2F%3Fcat%3Dflutter#8):

- `_loadRewardedAd()` method is not called, should be called at the bottom of `initState()`

- `_rewardedAd` should be nullable

- `_rewardedAd?.show` requires to implement callback `onUserEarnedReward`:
`_rewardedAd?.show(onUserEarnedReward: (_, reward) {QuizManager.instance.useHint();},`

**Comment by rickbsgu** [comment]
Thanks for this - I was really scratching my head.

Authors: How about fixing the tutorial??!!

**Comment by kunny** [comment]
Done updating the doc. Thanks for reporting!
