### ISSUE TITLE
Stuck at Adding Firebase to iOS/Android apps

### ISSUE THREAD

**Issue by rgvag** [googlecodelabs/admob-ads-in-flutter#2]
<img width="796" alt="Screen Shot 2020-08-08 at 9 16 08 AM" src="https://user-images.githubusercontent.com/8513416/89701792-d492e400-d957-11ea-87ea-265e9f82287f.png">
Spinner - Checking if the app has communicated with our servers. You may need to uninstall and reinstall your app.

Tried Running App several times. This issue never occurred before with any of the other Codelabs before.

**Comment by kunny** [comment]
You can skip that step. It just checks whether the Firebase server receives signals from your app, but sometimes it might take longer than usual.

Please feel free to start implementing the code. You can also check integration status by using StreamView or DebugView at any time.
