### ISSUE TITLE
Get Android V2 errors - package won't build

### ISSUE THREAD

**Issue by rickbsgu** [googlecodelabs/admob-ads-in-flutter#21]
Flutter 2.10.5, Dart 2.16.2, Doctor OK

Got V2 errors trying to build android.

Tried following the migration instructions but they were beyond confusing.  A lot of the changes looked like they were there already?

Launch fails on both emulators.

**Comment by kunny** [comment]
Hello all - the sample code has been updated. It should include the fix for the issues reported so far :)
