### ISSUE TITLE
Problems on m1 mac with android emulator

### ISSUE THREAD

**Issue by rickbsgu** [googlecodelabs/admob-ads-in-flutter#22]
See Stackoverflow message [here](https://stackoverflow.com/questions/72116841/admob-issues-on-m1-mac-for-android).

Suspect this is a bug, but maybe it will get eyes from the developers here.

**Comment by kunny** [comment]
Hey Rick, I tried to reproduce it on my end (with MBP M1 16-inch, Android emulator with arm64 system image), but I couldn't find any issues. Would you try creating an AVD with arm64 system image and run the app again?
