### ISSUE TITLE
Needs update!!!

### ISSUE THREAD

**Issue by rickbsgu** [googlecodelabs/admob-ads-in-flutter#23]
Had to fix a whole bunch of warnings to get this to work.  Despite being only a year old, it's way out of date.
Authors need to bring this up to date.

Here is a working version (no starter/complete folders, just the project with tags - name is changed): https://github.com/rickbsgu/my_admob_tutorial
There is a 'starter' tag you can use to follow the tutorial, if you want.

Note there is an issue with android on an m1 mac.  I've reported that in #22, with a Stackoverflow link: https://stackoverflow.com/questions/72116841/admob-issues-on-m1-mac-for-android

**Comment by Aztal-Samoht** [comment]
one specific issue is that on step 9 the guide uses ```_rewardedAd!.show()``` when RewardedAd's .show() method requires a Function as an argument these days.

**Comment by rickbsgu** [comment]
Thanks for the input.

Can you point me to a reference that spells that out?

**Comment by kunny** [comment]
Hello all - the sample code has been updated! It should include the fix for the issues reported so far :)
