### ISSUE TITLE
Bool variable _isInterstitialAdReady used but not declared

### ISSUE THREAD

**Issue by yamhoresh** [googlecodelabs/admob-ads-in-flutter#26]
Hi Taeho, great codelab!

I believe there's a mistake in the first code block on the 8th page of the codelab (for ["Add an interstitial ad"](https://codelabs.developers.google.com/codelabs/admob-ads-in-flutter?hl=en#7)).
The very last line in the _loadInterstitialAd() function sets `_isInterstitialAdReady = false;`, however this variable wasn't previously defined.

This snippet does not exist in the GitHub repo here, so I'd assume this is just a mistake in the codelab website:

![image](https://user-images.githubusercontent.com/48316647/186914886-2f874ded-4284-4166-9017-3a9256bef646.png)

Thanks in advance!

**Comment by kunny** [comment]
Thanks for your report! I've updated the doc to exclude the obsolete code snippet. :)
