### ISSUE TITLE
'google_mobile_ads' plugin instability.

### ISSUE THREAD

**Issue by AndersonFiorini** [googlecodelabs/admob-ads-in-flutter#7]
I am having performance problems when using the "google_mobile_ads" plugin. Problems scrolling and crashing apps on devices running android 8 and earlier. The examples "https://codelabs.developers.google.com/codelabs/admob-ads-in-flutter" and  "https://codelabs.developers.google.com/codelabs/admob-inline-ads-in-flutter" are very problematic running on both emulators and real devices.  This plugin is very unstable.

**Comment by kunny** [comment]
Could you file an issue on https://github.com/googleads/googleads-mobile-flutter/issues instead? Also, if you got a crash, please include the crash log as well so the plugin dev team can figure out what's happening on your end.
