### ISSUE TITLE
Mention wrong  File in Step 6

### ISSUE THREAD

**Issue by ukuellmarks** [googlecodelabs/admob-ads-in-flutter#8]
Hi,
Step 6 of this code lab referenced lib/home_page.dart to apply the changes. This File does not exist. I checked the complete source tree and here the changes gets applied to lib/home_route.dart

Looks like  the wrong file is mention the the Text.

**Comment by kunny** [comment]
Thanks for the report! Just updated the content that fixes this issue: https://codelabs.developers.google.com/codelabs/admob-ads-in-flutter#5
